### ISSUE TITLE
rmlint with FIEMAP is slow on large dataset

### ISSUE THREAD

**Issue by vvs-** [sahib/rmlint#120]
In my testing `rmlint -b --without-fiemap` is way faster than `rmlint -b`. Profiling shows that most of the time is spent in g_sequence_search. I suspect that current implementation shows O(n^2) behavior on fragmented files. I created a test case which should demonstrate it. Create two directories and run `seq 259 | while read n; do fallocate -l 4194304 $n; seq 0 8192 4194304 | xargs -I xxx fallocate -p -o xxx -l 4k $n; done` inside it. While this test case is artificial, it exhibits the same symptoms as the real system.

**Comment by SeeSpotRun** [comment]
Nice pickup.
I think the problem is that we lookup the fiemap offset in GSequence each time we re-sort the files into disk offset order.  If we store the file's current disk offset in the RmFile structure and only update it when required then the problem should go away.
Actually it probably makes sense to to away with the GSequence altogether and just get updates from the filesystem as required.  All we really need to store is the current fragment's disk offset and endpoint.

**Comment by SeeSpotRun** [comment]
Which branch was the above testing on btw?

**Comment by vvs-** [comment]
It was b129efaf1b94d6dd36720882d674a02fcc6b1f5f

**Comment by sahib** [comment]
Hi @vvs-,

it should be a bit better as of 2e6774d528ad41e236d5fbd03e18f728cd1ef31b. 
In my testcase it has gone to ~40 seconds from ~60 seconds. Without fiemap it's still around 25 second, so that's still faster.

Im not sure if that's the final fix yet - the files in your testcases have 512 extents which stresses the current seek optimisation strategy. That causes rmlint to read all the files in only 8K blocks, which is darn slow. Without fiemap it will just double the read size on every iteration. Not sure if all the fragmentation stuff is really a good idea.

=> Needs some benchmarking before closing this.

**Comment by vvs-** [comment]
Yes, that test is purely artificial and could be misleading. Unfortunately, that's the best what I've come up with. But nevertheless I can see even bigger improvement on my computer: the time went from 256s to 47s. I'll do a full test on a real data set, which should show it for real.

**Comment by SeeSpotRun** [comment]
Part of the problem is the time taken to look up the fiemap data in the first place.
Then I suspect on large datasets, we lose the benefit because the kernel's fiemap cache gets pushed out by the large volume of data we are reading in.  So when we ask the the next file increment (which is conveniently located close to the current disk head position), the kernel has to go and look up the files fiemap data first, which probably involves moving the disk head.  So we lose any benefit, unless we can find a way to force the kernel to keep the fiemap data in memory.  It looks like Ted T'so was trying to add this capability into ext4 a while back but met with some resistance (http://lists.openwall.net/linux-ext4/2013/07/22/8).  It's a fairly long discussion and I'm not sure what was the final result.
Meanwhile, while it seems a shame, I'm thinking we should disable the fiemap "optimisation" by default in the upcoming release.

**Comment by sahib** [comment]
@SeeSpotRun: Out of curisoity, do you have any timing how long fiemap takes on a big dataset usually compared to the other timings? (Can't test myself, since on ssd only laptop currently again).

Regarding the intra-increment optimisation: I guess we were trying to be more clever than the kernel here.  :smile:

Regarding ```-pp```: I guess disabling it for now is sensitive. Although I guess it should work okay with higher memory limit for most typical usecases...

**Comment by vvs-** [comment]
Actually, there is almost no difference in performance without `-pp` option on the above test case. Also, I see no memory issues with it.

SeeSpotRun/rmlint@49a25ed8f735f3ba253076437931f442445f2126 is broken and was fixed only in SeeSpotRun/rmlint@df1af735f5bd8212b39d317fc762a665fb44ff31. Unfortunately, that one contains other non-related stuff as well. The test case ran successfully though. I'll need to check it on the full data tonight.

**Comment by SeeSpotRun** [comment]
Sorry I'm still learning how to work using git properly and still get tangled up with multiple branches.

For benchmarking without the "other non-related stuff" try https://github.com/SeeSpotRun/rmlint/tree/no-intra-segment-fiemap-optimisation which is basically https://github.com/sahib/rmlint/tree/develop plus cherry-picked SeeSpotRun/rmlint@49a25ed plus the paranoid memory manager fix https://github.com/SeeSpotRun/rmlint/commit/693087f.

**Comment by SeeSpotRun** [comment]
@sahib, I'm struggling to see any significant benefit in any real-world scenario at the moment.
Yes we are trying to be more clever than the kernel; unfortunately it's not smart enough to take advantage of our attempts to make its job easier.  What's missing is some equivalent of fadvise() when we do the initial fiemap lookup, to tell the kernel to keep fiemap data cached.

**Comment by vvs-** [comment]
Thanks.

I don't mind trying other stuff but it makes comparing results difficult. For the record, I've tested it with all other changes and it ran for 11h 4m which is better. But the baseline timing could have changed as well, so I'm not sure if it make sense. I'll test your new branch tonight and post the results.

**Comment by SeeSpotRun** [comment]
@vvs- if you're in the mood to try things out, please try https://github.com/SeeSpotRun/rmlint/tree/debottlenecking which is giving very promising results in early testing, particularly for -pp option.  It pulls in several new optimisations and enhancements from https://github.com/sahib/rmlint/tree/develop, https://github.com/sahib/rmlint/tree/pathtricia, https://github.com/SeeSpotRun/rmlint/tree/no_hash_wait plus a new threading strategy

**Comment by vvs-** [comment]
Yes, it improved baseline test time (`-T df -pp -b --without-fiemap`) by 4%, i.e. it ran for 7h 47m.

**Comment by SeeSpotRun** [comment]
Was hoping for a little more but I guess it depends on disk speed and number of cpu's.  I'm seeing much bigger percentage improvements, particularly with fast disk (SSD) and large number of cpu's (6).

**Comment by vvs-** [comment]
Right, in my setting it's mostly I/O bound. I suppose you get more speed if a storage is capable of more IOPS. Otherwise CPUs will starve.

**Comment by sahib** [comment]
@vvs-: I guess the original issue is resolved and this issue can be closed for now?

**Comment by vvs-** [comment]
Well, I don't know. It's not CPU bound anymore, but still noticeably slower than `--without-fiemap`. If this can't be helped, then I guess it can be closed. It's your decision anyway.

**Comment by sahib** [comment]
Closing for now, but we will have some discussion about that at some point internally (especially when it comes to supporting sparse files).

**Comment by SeeSpotRun** [comment]
May have resolved the issue (https://github.com/SeeSpotRun/rmlint/tree/fiemap)

vvs-'s test case runs in about the same time regardless of with-or-without fiemap.

Testing on a rotational copy of /usr gives (average of 1 run each):
rmlint/master 290s with / 206 without fiemap
https://github.com/SeeSpotRun/rmlint/tree/fiemap 212s with / 208 without fiemap.

Testing on part of /home (average of 1 run each) gives:
rmlint/master 361s with / 339 without fiemap
https://github.com/SeeSpotRun/rmlint/tree/fiemap 258s with / 350 without fiemap.

So in synthetic cases it's no slower and in at least one real-world case it looks significantly faster...

**Comment by SeeSpotRun** [comment]
I've run a few repeats and the above results are repeatable (ie up to 25% improvement in one case).
@vvs- - if you have a chance to run your 8-hour real-world test case again (https://github.com/SeeSpotRun/rmlint/tree/fiemap with fiemap enabled of course) I'd be interested in the results.

**Comment by SeeSpotRun** [comment]
@vvs- actually please use https://github.com/SeeSpotRun/rmlint/tree/fiemap-2.  I made a mess of my git workflow in https://github.com/SeeSpotRun/rmlint/tree/fiemap.

**Comment by vvs-** [comment]
Thanks.

The test ran for 8h 11m. That's marginally slower than `--without-fiemap`. It is a clear improvement compared to previous results.

**Comment by SeeSpotRun** [comment]
Thanks for the feedback.
New test branch https://github.com/SeeSpotRun/rmlint/tree/oscar includes a couple more optimisations if you're still in the testing mood.
Out of curiosity, are you setting --max-paranoid-mem on your tests or leaving it at the default 256M?

**Comment by vvs-** [comment]
I'm using the default. I guess that on 2G using more would just hurt performance.

**Comment by sahib** [comment]
@vvs-; Regarding memory usage, can you check the peak/average usage if you decide to re-run?
There was some stuff that should lower the memory footprint a bit, especially with paranoid.

**Comment by vvs-** [comment]
This time it was 8h 4m, i.e. almost the same.

I didn't look at the memory usage, but will look next time.

**Comment by SeeSpotRun** [comment]
The last commit shouldn't make more than a few seconds difference.
What's the underlying fs by the way?  I'm working on a fix for a btrfs-related fiemap issue (subvolumes look like separate partitions which messes up file sorting by FIEMAP offset) but that won't help you unless you're running btrfs.

**Comment by vvs-** [comment]
It's an ext4.
