### ISSUE TITLE
--replay doesn't work with -D

### ISSUE THREAD

**Issue by misieck** [sahib/rmlint#383]
`rmlint  -Dkm   /media/user/DiskS/ // /media/user/DiskL/`
produces long lists of:
  \# Empty dir(s)
  \# Empty file(s)
  \# Duplicate Directorie(s)
  \# Duplicate(s)

If immediately followed by 
`rmlint --replay rmlint.json -Dkm   /media/user/DiskS/ // /media/user/DiskL/`
lists only
  \# Duplicate(s)
and it includes exactly as many elements as the previous \#Duplicates, resulting in much fewer duplicates found.

Similarly, 
`rmlint  -km   /media/user/DiskS/ // /media/user/DiskL/`
followed by
`rmlint  --replay rmlint.json -Dkm   /media/user/DiskS/ // /media/user/DiskL/`
doesnt produce the expected # Duplicate Directorie(s) either.

**Comment by misieck** [comment]
I expected rmlint to produce an universal json file, that could be used to replay in any configuration.
For this to work, the json file would need to always include all the individual duplicates found (to use --replay after initial -D), and all the unique files found or number of dir entries per dir (to use --replay -D after initial  not-D)

**Comment by sahib** [comment]
Hello @misieck,

I agree on what you say. This behavior is confusing, to say the least.
However, I'm not sure with your proposed solution (i.e. a universal ``.json`` file).

Currently the ``.json`` file has the useful property that you can parse each entry, extract each ``type=duplicate_file`` or ``type=duplicate_dir`` from that and do something with the list of duplicates.
When including the same both ``duplicate_file`` and ``duplicate_dir`` this would overlap and break users that rely on this - also it would increase the ``.json`` size quite a bit, especially when you include unique files too.

I need to look into it a bit more, maybe we can make ``--replay`` to unpack directories in the ``-D to non -D`` case and pack them in the ``non -D to -D`` case. The latter is of course a bit difficult, since directories might change apart from the duplicates we found in it, but we can probably handle this.

As a quick action I will add a note about this in the ``--replay`` documentation.

Also for completeness, what version of ``rmlint`` are you using?

**Comment by misieck** [comment]
My version is:
version 2.8.0 compiled: Jan 28 2019 at [00:31:11] "Maidenly Moose" (rev 3)
compiled with: +mounts +nonstripped +fiemap +sha512 +bigfiles +intl +replay +xattr +btrfs-support

I'm sure you know this, youcould have new generic database file as an option if you want to keep backwards compatibility, or extend the old one without breaking the old types (e.g. add type=duplicate_file_in_duplicate_dirs).
Quick thought: Since the json is used by some kind of replay and using -D with --replay looks very broken to me (I dont think anyone would use rmlint this way), so you could possibly make the new behavior default when -D is in use. 

A word of personal motivation =):
I like rmlint because of the ability to scan once (time consuming) and process in quick steps.
( ... and a simple way to select unwanted duplicates that actually makes sense  "-km //" - that's a real game changer).
The duplicate directory option is very useful - its a better indication of a real waste, rather than sometimes necessary duplicated file.
Joining those abilities would really make for a much better tool, allowing to faster delete more garbage with less mistakes.

**Comment by sahib** [comment]
> I'm sure you know this, youcould have new generic database file as an option if you want to keep backwards compatibility, or extend the old one without breaking the old types (e.g. add type=duplicate_file_in_duplicate_dirs).

We had a database option in earlier  versions, but that turned out to be problematic for it's own reasons. Another lint type for those might work as alternative option.

> A word of personal motivation =):
> [...]

Thanks, your proposal makes sense to me as an improvement. I just need to find the time to implement it - it's sadly a bit hard to find time and motivation beside my day job to do that. But granted enough time it will be implemented - probably over christmas latest. :)

By the way, I added a word of warning about this behavior in the [manpage for now](https://github.com/sahib/rmlint/commit/41918398d9e3ea105609c1d980dfff76d7405d53).

**Comment by sahib** [comment]
Okay, some time have passend and I finally got around to implement this. You can try it out in the ``features/replay-treemerge`` branch. Took some time since both ``-D`` and ``--replay`` are quite complex features, so bringing both together required some refactoring and thus possibly some breakage. Luckily the tests pass again, so it should be mostly fine.

I tried it out in the following way:

```
# This was the data set, all 'x' files have the same content:
$ tree /tmp/dupes-nested
├── a
│   ├── empty
│   ├── special
│   ├── sub1
│   │   ├── x1
│   │   └── x2
│   ├── sub2
│   │   └── x3
│   └── sub2_copy
│       └── x3
├── b
│   ├── empty
│   ├── special
│   ├── sub1
│   │   ├── x1
│   │   └── x2
│   ├── sub2
│   │   └── x3
│   └── sub2_copy
│       └── x3
└── special

```

```
# unpacking directories:
$ ./rmlint /tmp/dupes-nested -D                     

# Empty file(s):
    rm '/tmp/dupes-nested/b/empty'
    rm '/tmp/dupes-nested/a/empty'

# Duplicate Directorie(s):
    ls -la '/tmp/dupes-nested/a'
    rm -rf '/tmp/dupes-nested/b'
    ls -la '/tmp/dupes-nested/a/sub2'
    rm -rf '/tmp/dupes-nested/a/sub2_copy'

# Duplicate(s):
    ls '/tmp/dupes-nested/a/special'
    rm '/tmp/dupes-nested/special'
    ls '/tmp/dupes-nested/a/sub1/x1'
    rm '/tmp/dupes-nested/a/sub1/x2'
    rm '/tmp/dupes-nested/a/sub2/x3'
$ ./rmlint /tmp/dupes-nested --replay rmlint.json   
INFO: Loading json-results `/home/sahib/code/rmlint/rmlint.json'
INFO: »/home/sahib/code/rmlint/rmlint.json« was created with -D, but you're running without.
INFO: rmlint will unpack duplicate directories into individual files.
INFO: If you do not want this, pass -D to the next run.

# Empty file(s):
    rm '/tmp/dupes-nested/a/empty'
    rm '/tmp/dupes-nested/b/empty'

# Duplicate(s):
    ls '/tmp/dupes-nested/b/special'
    rm '/tmp/dupes-nested/a/special'
    rm '/tmp/dupes-nested/special'
    ls '/tmp/dupes-nested/a/sub1/x1'
    rm '/tmp/dupes-nested/b/sub1/x1'
    rm '/tmp/dupes-nested/a/sub1/x2'
    rm '/tmp/dupes-nested/b/sub1/x2'
    rm '/tmp/dupes-nested/a/sub2/x3'
    rm '/tmp/dupes-nested/b/sub2/x3'
    rm '/tmp/dupes-nested/a/sub2_copy/x3'
    rm '/tmp/dupes-nested/b/sub2_copy/x3'
```

```
# packing directories:
$ ./rmlint /tmp/dupes-nested                         

# Empty file(s):
    rm '/tmp/dupes-nested/b/empty'
    rm '/tmp/dupes-nested/a/empty'

# Duplicate(s):
    ls '/tmp/dupes-nested/special'
    rm '/tmp/dupes-nested/a/special'
    rm '/tmp/dupes-nested/b/special'
    ls '/tmp/dupes-nested/b/sub1/x1'
    rm '/tmp/dupes-nested/a/sub1/x1'
    rm '/tmp/dupes-nested/b/sub1/x2'
    rm '/tmp/dupes-nested/a/sub1/x2'
    rm '/tmp/dupes-nested/b/sub2/x3'
    rm '/tmp/dupes-nested/a/sub2/x3'
    rm '/tmp/dupes-nested/a/sub2_copy/x3'
    rm '/tmp/dupes-nested/b/sub2_copy/x3'
$ ./rmlint /tmp/dupes-nested --replay rmlint.json -D
INFO: Loading json-results `/home/sahib/code/rmlint/rmlint.json'
INFO: »/home/sahib/code/rmlint/rmlint.json« was created without -D, but you're running with.
INFO: rmlint will pack duplicate files into directories where applicable.
INFO: If you do not want this, omit -D from the next run.

# Empty file(s):
    rm '/tmp/dupes-nested/a/empty'
    rm '/tmp/dupes-nested/b/empty'

# Duplicate Directorie(s):
    ls -la '/tmp/dupes-nested/a'
    rm -rf '/tmp/dupes-nested/b'
    ls -la '/tmp/dupes-nested/a/sub2'
    rm -rf '/tmp/dupes-nested/a/sub2_copy'

# Duplicate(s):
    ls '/tmp/dupes-nested/a/special'
    rm '/tmp/dupes-nested/special'
    ls '/tmp/dupes-nested/a/sub1/x1'
    rm '/tmp/dupes-nested/a/sub1/x2'
    rm '/tmp/dupes-nested/a/sub2/x3'
```

Please test this.

**Comment by misieck** [comment]
Sorry for the delay. I executed some quick tests and your fix looks to work pretty well in packing files out of and into directories. 
I have found some problems/inconsistencies. Some of them should probably get separate issues, but ill post them here for now:

Based on a scenario of two identical directory trees, "one" and "two", where one is a redundant copy of two, so ideally rmlint should remove "one" completely.

1) --replay produces wrong summary on Identical searches with -D compared to the first run. Number of duplicates is incorrectly reported.
`rmlint -D -T df,dd -km  one // two`
`rmlint --replay rmlint.json -D -T df,dd -km  one // two`

2) --see-symlinks is default but only works when -D is used. Duplicate symlinks are not recognized as duplicate files, unless -D is in effect (even if symlink is outside of duplicate dir). symlinks disappear also when --replay is used (even if -D is used). This is not a new issue.

3) Bad symlinks are completely ignored and prevent removal of otherwise duplicate directories (with -T dd,df), even with -D, when good symlinks are detected and duplicates removed.

4) Problems in interaction of -D and -T dd with regards of inclusion of hidden files and directories. 
-D -T dd,df includes different set of hidden files and directories than -T dd,df 
This is a regression in the fix version against 2.8.0.

5) When starting with json created without -D, all hidden files are missing. -r adds all hidden files. But following with --reply -D without -r, it still includes ALL hidden files (I expect same result on the last two calls): 
`rmlint -rkm one // two`
`rmlint --reply rmlint.json -Dkm one // two`
`rmlint -Dkm one // two`

7) -T df,dd produce effect very similar to -D -T df,dd in that it shows "Duplicate Directories" and "Duplicate files" , but doesn't include --see-symlinks. I got a bit confused when I got Duplicate Dirs without -D. But maybe thats intended.

**Comment by sahib** [comment]
Hello @misieck,

thanks for having a try. I will check those points in detail over the next few days/weeks. I have some quick remarks though:

> --replay produces wrong summary on Identical searches with -D compared to the first run. Number of duplicates is incorrectly reported.
rmlint -D -T df,dd -km one // two
rmlint --replay rmlint.json -D -T df,dd -km one // two

This should be mostly fixed as of 21a1e218287695e33d295a63bbc8b1f82e4a0960. If the problem persists (probably due to hidden files / symlinks), please include a small test set that shows the behavior.

> --see-symlinks is default but only works when -D is used. Duplicate symlinks are not recognized as duplicate files, unless -D is in effect (even if symlink is outside of duplicate dir). symlinks disappear also when --replay is used (even if -D is used). This is not a new issue.

The symbolic link situation is quite confusing in general. ``--see-symlinks`` treats symbolic links like files that have only the path to the target inside. This also means that bad symbolic links are not found by default. Why this was chosen as default probably deserves another paragraph, but you might be lucky if you try with ``-f``.

> Bad symlinks are completely ignored and prevent removal of otherwise duplicate directories (with -T dd,df), even with -D, when good symlinks are detected and duplicates removed.

Please try with ``-f``. Maybe it's time to think about the default again.

> When starting with json created without -D, all hidden files are missing. -r adds all hidden files. But following with --reply -D without -r, it still includes ALL hidden files (I expect same result on the last two calls): [...]

True, that's definitely a bug.

> -T df,dd produce effect very similar to -D -T df,dd in that it shows "Duplicate Directories" and "Duplicate files" , but doesn't include --see-symlinks. I got a bit confused when I got Duplicate Dirs without -D. But maybe thats intended.

It is. ``-D`` is just a convenience option.

**Comment by misieck** [comment]
If --see-symlinks treats them as small files with a path inside, why are bad links not detected? After all why should it matter if the destination is not there - its just a path.
For my use case -f (followlinks) is not a solution. Currently I use rmlint to clear old backup copies of my filesystems - they are full of symlinks to all kind of places (such as the .wine profiles with links to /home/myuser and /), so following links is definitely not what I want to do. 
Just treat them like small files with path in them. The manual claims this is exactly what rmlint is supposed to do by default, but it doesn't seem to be the case.
I opened a separate ticket for this for your convenience =)

**Comment by sahib** [comment]
Okay, I worked on some of the points:

1. **Wrong replay summary:** Hopefully fixed by 21a1e218287695e33d295a63bbc8b1f82e4a0960. If it persists: examples are always helpful.
2. **Symlinks not seen by default**: This should be fixed as of 37e0c81c99648b35058ef2fbfaca89ee7fdd8b75 and 40d6233cea1ca715e8273bea0d64d45ae6467e0a.
3. **Bad links not used with -T df,dd**: Should be fixed as 3591f565cee715aef8afa84c4108e1c03ec991e1.
4. **interaction of -D and -T dd**: I gonna need an example on this one.
5. **--replay with -D and -r**: Should be fixed as of 682064503954695cc48a7a7b1a993bcff0a998f7.
6. [-D is just a shortcut for some more options one can overwrite afterwards](https://github.com/sahib/rmlint/blob/develop/lib/cmdline.c#L1096).

Those fixes were of general nature and were also merged into ``features/replay-treemerge``.

**Comment by misieck** [comment]
[onetwo.tar.gz](https://github.com/sahib/rmlint/files/4146571/onetwo.tar.gz)

1. Unfortunately 21a1e21 doesn't fix it. Looks like the replay summary only counts displayed items (each dir counts as one item), instead of total files. 
`rmlint -D -T df,dd -km one // two`
`rmlint --replay rmlint.json -D -T df,dd -km one // two`

2. Symlinks are now included! But with --replay symlinks get a warning 
`modification time of ``/path/test/one/goodlink`` changed. Ignoring.`
This removes the symlink from results. Bad symlinks unaffected.

3. Bad links are now included!.

4. There is a difference between the following two:
`rmlint -T df,dd -km one // two`
`rmlint -D -T df,dd -km one // two`
The first one includes hidden files and directories and the second only if they are part of a duplicate dir.

5. --replay -D after -r: the fix went too far =). Now all hidden files disappear, even inside duplicate dirs, preventing those dirs from being reported (--partial-hidden not applied?).

Found more issues:

7. --replay -T dd gives empty result, even for trivial cases

8. Empty files prevent duplicated directories from being found with -T dd, without -T ef

9. --replay ignores -km (or maybe just -k) and deletes indiscriminately bad links and empty files, if json was made without -km.
 
10. --replay -T bl doesn't detect bad links if the json was made without  -T bl. Similarly --replay -T df doesn't put bad links in duplicates if the json was made with -T df,bl. Same applies to empty files. 
A need to unpack the other lint categories (bad link, empty file ...) with --replay?

**Comment by sahib** [comment]
1. Ah, I see. This is a bit harder to fix, thus it might take a bit longer due to the usual time constraints.
2. Should be fixed as of 7d1a55bf744a1d2fac6237b78f4a0693938f2b1a.
3. Good.
4. I'm still confused. Do you have a full example with expected output? It's time consuming for me to get into the list of issues, so this will help. Also, I would be interested to see if this commit (7dfc439d51ea618e711923761469392b57f41016) makes a difference on this matter.
5. Confirmed, I need to work on that still.

----

7. This  appears to work for me. Full example please. While testing I accidently messed up the path, so that's why it didn't find something for me.
8. That's kinda expected. It will probably work if you do ``--size 0`` (i.e. handle empty files as duplicates). That's still a bit confusing, and it might be good to enable it automatically when it's not set explicitly, duplicate directories are searched and empty files are not considered otherwise.
9. A full example would be helpful again and will save me some time. Alternatively this could be added to the documentation.
10. ``--replay`` is not supposed to actually traverse the file system. If you want bad links in the output, create the json file with ``-T bl``.  This is actually the reason I didn't want to do this feature initially - because all the edge cases there would be and since there is no clear line on how far to go.

**Comment by SeeSpotRun** [comment]
Hi, I'm just going through old issues and looking to close this one out.

Point (1) still seems to be a problem though (different summary reported for `--replay`).  That's somewhat cosmetic so I can live with that.
Points (1) through (5) all seem resolved now.
Point (6) is a little confusing but behaving as designed.
I am able to reproduce (7):
```
$ rmlint one two
<gives expected output>
$ rmlint --replay rmlint.json -T dd one // two
<no duplicates found>
$ rmlint --replay rmlint.json -T dd,df one // two
<gives expected output>
```
Point (8) can perhaps be worked around as noted above via `--size 0`
I can reproduce (9) ie `-k` directive not respected for bad links and empty files.
Point (10) is operating as designed.

**Comment by SeeSpotRun** [comment]
I think there are two underlying issues with `--replay`:

* No checking for additional files, ie relies on what's in the `.json` file.  This limits usecases to fairly immediate re-runs.  It also creates limitations in combination with trying to find matching dirs via `-T dd`.
* The `--replay` implementation is more-or-less a parallel implementation of the main `rmlint` lint detection algorithm.  That means more code and hence more opportunities for logic errors.

I'm leaning towards a re-implementation of `--replay` which pre-processes the `.json` data in a way that can be fed into the main `rmlint` lint detection algorithm.  This should reduce total code base and also facilitate additional options to:
* re-scan for files that weren't included in the `.json` data
* add additional paths
* work with the new `--hash-unmatched` and `--hash-uniques` options.

**Comment by SeeSpotRun** [comment]
> I'm leaning towards a re-implementation of `--replay` which pre-processes the `.json` data in a way that can be fed into the main `rmlint` lint detection algorithm. 

Done: https://github.com/SeeSpotRun/rmlint/tree/new-replay

Happily, about 700 less lines of code now.

Test case (1) now gives identical output for original run and `--replay`.
Test case (9) now respects `-k` and `-m`.
Test case (7): still doesn't find duplicate dirs, still some more debugging needed but getting close...

**Comment by SeeSpotRun** [comment]
Obvious with hindsight; hidden files was the problem.
```
$ rmlint one two --hidden
<gives expected output>

$ rmlint --replay rmlint.json -T dd one // two
# Duplicate Directorie(s):
    ls -la '/pwd/one'
    rm -rf '/pwd/two'

$ rmlint --replay rmlint.json -T dd,df one // two
# Duplicate Directorie(s):
    ls -la '/pwd/one'
    rm -rf '/pwd/two'

# Duplicate(s):
    ls '/pwd/one/alink'
    rm '/pwd/one/badlinksinside/alink (copy)'
```

I think I can close this one out now...

**Comment by alichaudry** [comment]
> Obvious with hindsight; hidden files was the problem.
> 
> ```
> $ rmlint one two --hidden
> <gives expected output>
> 
> $ rmlint --replay rmlint.json -T dd one // two
> # Duplicate Directorie(s):
>     ls -la '/pwd/one'
>     rm -rf '/pwd/two'
> 
> $ rmlint --replay rmlint.json -T dd,df one // two
> # Duplicate Directorie(s):
>     ls -la '/pwd/one'
>     rm -rf '/pwd/two'
> 
> # Duplicate(s):
>     ls '/pwd/one/alink'
>     rm '/pwd/one/badlinksinside/alink (copy)'
> ```
> 
> I think I can close this one out now...

@SeeSpotRun is this issue resolved via #482 in this repo or your fork?

I came across this issue because I was also very confused by the replay behavior with and without the `-D` option. I had an `rmlint.json` file of a massive filesystem (~14 TB) and I was running a replay with the `-D` option on a small subset of my original fs, but I wasn't coming across any duplicated directories. Now I understand that it doesn't work because the original rmlint run was done sans the `--merge-directories` option.

Are there any risks in merging this updated replay logic into this primary repo? Or should the risks be taken care of via passing tests/builds?

**Comment by SeeSpotRun** [comment]
> Are there any risks in merging this updated replay logic into this primary repo?

I'll push it to the `develop` branch here, and it should end up in `master` on the next release.

**Comment by SeeSpotRun** [comment]
> Now I understand that it doesn't work because the original rmlint run was done sans the `--merge-directories` option.

It should be sufficient to do the original rmlint with `--hidden` option.

**Comment by SeeSpotRun** [comment]
I think the issue has been effectively covered and changes incorporated into `develop` branch.
