### ISSUE TITLE
Wrong number of duplicated displayed.

### ISSUE THREAD

**Issue by ghost** [sahib/rmlint#461]
I am running rmlint like this: `/root/rmlint-2.10.1/rmlint --limit-mem 2500M -mkgr -T dd /mnt/SEAGATE/ // /mnt/WD/`

The output is the following:

```
# /root/rmlint-2.10.1/rmlint --limit-mem 2500M -mkgr -T dd /mnt/SEAGATE/ // /mnt/WD/
���������������������������������������                             Traversing (1196900 usable files / 0 + 0 ignored files / folders)
���������������������������������������                                  Preprocessing (reduces files to 792057 / found 0 other lint)
���������������������������������������                   Matching (88875 dupes of 49077 originals; 0 B to scan in 0 files, ETA: 14s)
���������������������������������������                                                  Merging files into directories (stand by...)

==> In total 1196900 files, whereof 18446744073709524917 are duplicates in 6530 groups.
==> This equals 291.66 GB of duplicates which could be removed.
==> Scanning took in total  2h  1m 31.661s.

Wrote a json file to: /root/2020-12-18_sorting_hdd-running-rmlint-seagate-vs-wd/rmlint.json
Wrote a sh file to: /root/2020-12-18_sorting_hdd-running-rmlint-seagate-vs-wd/rmlint.sh
```

This is unlikely to be true, since 18 446 744 073 709 524 917 is an enormous number.

I am rmlinting two HDDs, of which one has ~1.5Tb of files, and the other one has ~400Gb.

**Comment by SeeSpotRun** [comment]
Sorry for delayed response.

I'm guessing the duplicate dirs (`-T dd`) file-counting logic is failing somewhere.  The value 18446744073709524917 is actually -26698 expressed as an unsigned 64-bit integer.

If you run with `-T df` do you get more sensible results?

**Comment by Cebtenzzre** [comment]
At first glance this looks like the issue fixed by https://github.com/cebtenzzre/rmlint/commit/3c969ee62bae4a6973548cd428e23f484696317c

**Comment by lockywolf** [comment]
The issue is still there.

```
==> Note: Please use the saved script below for removal, not the above output.
==> In total 57 files, whereof 18446744073709551615 are duplicates in 0 groups.
==> This equals 125.16 MB of duplicates which could be removed.
==> Scanning took in total 1.779s.

```

Those directories are small, and only differ by a single file, called `Markor_2021-11-27T15-46-51 (2).jpg
`

Note the space in the name.

**Comment by RayOei** [comment]
To reproduce:

```
#!/bin/sh

echo "======================#461======================="
rm -rf test
rm -rf test1

mkdir test
echo "testtest" > test/file1
echo "testtest" > test/file2

mkdir test1
echo "testtest" > test1/file1
echo "testtest" > test1/file2

rmlint -mkT dd test1 // test

echo "=================================================="

echo "test" >  test1/file3

rmlint -mkT dd test1 // test
```

First result shows duplicate directories

```
==>  Duplicate Directorie(s):
         ls -la <..>/test
         rm -rf <..>/test1
<...>
In total 4 files, whereof 1 are duplicates in 0 groups.
```

The 2nd result shows the large number

```
In total 5 files, whereof 18446744073709551614 are duplicates in 0 groups.
```

This error appears when the `k` switch is used together with `//` separator.

Running with the earlier suggested `df` switch:

`rmlint -mkT df test1 // test`

```
 Duplicate(s):
    ls '/Users/ray/Projects/rmlint-orig/test/file1'
    ls '/Users/ray/Projects/rmlint-orig/test/file2'
    rm '/Users/ray/Projects/rmlint-orig/test1/file1'
    rm '/Users/ray/Projects/rmlint-orig/test1/file2'

==> Note: Please use the saved script below for removal, not the above output.
==> In total 5 files, whereof 2 are duplicates in 1 groups.
```

**Comment by vassilit** [comment]
@RayOei have you tried with 3c969ee ?

**Comment by vassilit** [comment]
Could it be https://github.com/sahib/rmlint/commit/9b0fc662805c25fcd219388299a9a01dd0fbefd3 ?

**Comment by RayOei** [comment]
That commit doesn't exist in the repo. I compared it to the current `preprocessor.c` but lines do not match (at all) and the mentioned `traversed_folders` doesn't exist as a member of the struct `RMsession`. So I assume it was based on other changes as well? It seems to be based on [4d28a4d](https://github.com/sahib/rmlint/commit/4d28a4d58f17af32a3be9a12736404bf25003918) so it seems to exist on `develop` but not on `master`.

**Comment by RayOei** [comment]
That specific change doesn't exist on `develop`.

**Comment by vassilit** [comment]
I will look at it tomorrow. 

```
(gdb) watch self->session->dup_counter
Watchpoint 2: self->session->dup_counter
(gdb) continue
Continuing.

Thread 1 "rmlint" hit Watchpoint 2: self->session->dup_counter

Old value = 2
New value = 18446744073709551615
0x0000555555574564 in rm_tm_extract (self=self@entry=0x5555555d1710) at lib/treemerge.c:972
972	                self->session->dup_counter -= file_list->length - 1;

```

**Comment by RayOei** [comment]
You are fast 🚅  😁
